# Generated by Django 4.2 on 2023-04-05 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangovue', '0002_remove_measurement_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorType',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='variant',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='unit',
            name='precision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='unit',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='djangovue.sensortype'),
            preserve_default=False,
        ),
    ]
